// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcJpgCu3WnLOitf8jgkatM8DNj4xGQOrE',
    appId: '1:836345375454:web:77395477902ca7f1bf304f',
    messagingSenderId: '836345375454',
    projectId: 'dabblersportapp',
    authDomain: 'dabblersportapp.firebaseapp.com',
    storageBucket: 'dabblersportapp.firebasestorage.app',
    measurementId: 'G-RXQHPW85NV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANuXa9tsj6aIo7SXA0a4G_crkRqrFACoE',
    appId: '1:836345375454:android:9839f39188a3f662bf304f',
    messagingSenderId: '836345375454',
    projectId: 'dabblersportapp',
    storageBucket: 'dabblersportapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsU0fMA0L_BmHzHOkS-whgs0KpDnemaq8',
    appId: '1:836345375454:ios:f999ace6319832debf304f',
    messagingSenderId: '836345375454',
    projectId: 'dabblersportapp',
    storageBucket: 'dabblersportapp.firebasestorage.app',
    iosBundleId: 'com.example.dabbler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsU0fMA0L_BmHzHOkS-whgs0KpDnemaq8',
    appId: '1:836345375454:ios:80db17f14621c41ebf304f',
    messagingSenderId: '836345375454',
    projectId: 'dabblersportapp',
    storageBucket: 'dabblersportapp.firebasestorage.app',
    iosBundleId: 'com.dabbler.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcJpgCu3WnLOitf8jgkatM8DNj4xGQOrE',
    appId: '1:836345375454:web:a169e48491f8a861bf304f',
    messagingSenderId: '836345375454',
    projectId: 'dabblersportapp',
    authDomain: 'dabblersportapp.firebaseapp.com',
    storageBucket: 'dabblersportapp.firebasestorage.app',
    measurementId: 'G-B72GGZ7HVM',
  );
}
