import 'dart:ui' show Color;

const theme = (
  profile: (
    primary: Color(0xFFF6AA4F),
    onPrimary: Color(0xFF3F2600),
    primaryContainer: Color(0xFFFFF4CC),
    onPrimaryContainer: Color(0xFF2A1700),
    secondary: Color(0xFF703900),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFFFFBEE),
    onSecondaryContainer: Color(0xFF251100),
    tertiary: Color(0xFFAD8A67),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFFFE5CC),
    onTertiaryContainer: Color(0xFF2C1707),
    error: Color(0xFFBA1A1A),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFDAD6),
    onErrorContainer: Color(0xFF410002),
    background: Color(0xFFFFFBFF),
    onBackground: Color(0xFF1F1B16),
    surface: Color(0xFFFFFBFF),
    onSurface: Color(0xFF1F1B16),
    surfaceVariant: Color(0xFFEDE1D2),
    onSurfaceVariant: Color(0xFF4D4639),
    outline: Color(0xFF7F7667),
    outlineVariant: Color(0xFFD1C5B7),
    surfaceTint: Color(0xFFF6AA4F),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFF34302A),
    inverseOnSurface: Color(0xFFF8F0E7),
    inversePrimary: Color(0xFFFFB870),
    primaryFixed: Color(0xFFFFE0B3),
    onPrimaryFixed: Color(0xFF2A1700),
    primaryFixedDim: Color(0xFFFFB870),
    onPrimaryFixedVariant: Color(0xFF603E00),
    secondaryFixed: Color(0xFFFFDDBC),
    onSecondaryFixed: Color(0xFF251100),
    secondaryFixedDim: Color(0xFFFFBA80),
    onSecondaryFixedVariant: Color(0xFF552C00),
    tertiaryFixed: Color(0xFFFFE5CC),
    onTertiaryFixed: Color(0xFF2C1707),
    tertiaryFixedDim: Color(0xFFD6BA96),
    onTertiaryFixedVariant: Color(0xFF6B5139),
    surfaceDim: Color(0xFFE2DCD3),
    surfaceBright: Color(0xFFFFFBFF),
    surfaceContainerLowest: Color(0xFFFFFFFF),
    surfaceContainerLow: Color(0xFFFCF5EC),
    surfaceContainer: Color(0xFFF6EFE6),
    surfaceContainerHigh: Color(0xFFF0EAE1),
    surfaceContainerHighest: Color(0xFFEBE4DB),
  ),
);
