// Mocks generated by Mockito 5.4.6 from annotations
// in dabbler/test/features/notifications/presentation/controllers/notifications_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dabbler/core/fp/failure.dart' as _i6;
import 'package:dabbler/core/fp/result.dart' as _i2;
import 'package:dabbler/features/notifications/data/models/notification_model.dart'
    as _i5;
import 'package:dabbler/features/notifications/data/notification_realtime_service.dart'
    as _i7;
import 'package:dabbler/features/notifications/data/notifications_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T, E> extends _i1.SmartFake implements _i2.Result<T, E> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NotificationsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationsRepository extends _i1.Mock
    implements _i3.NotificationsRepository {
  MockNotificationsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i5.AppNotification>, _i6.Failure>> getPage({
    int? limit = 20,
    DateTime? cursor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPage, [], {#limit: limit, #cursor: cursor}),
            returnValue:
                _i4.Future<
                  _i2.Result<List<_i5.AppNotification>, _i6.Failure>
                >.value(
                  _FakeResult_0<List<_i5.AppNotification>, _i6.Failure>(
                    this,
                    Invocation.method(#getPage, [], {
                      #limit: limit,
                      #cursor: cursor,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<List<_i5.AppNotification>, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<void, _i6.Failure>> markAsRead(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [id]),
            returnValue: _i4.Future<_i2.Result<void, _i6.Failure>>.value(
              _FakeResult_0<void, _i6.Failure>(
                this,
                Invocation.method(#markAsRead, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<void, _i6.Failure>> markClicked(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markClicked, [id]),
            returnValue: _i4.Future<_i2.Result<void, _i6.Failure>>.value(
              _FakeResult_0<void, _i6.Failure>(
                this,
                Invocation.method(#markClicked, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<void, _i6.Failure>> markAllRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllRead, []),
            returnValue: _i4.Future<_i2.Result<void, _i6.Failure>>.value(
              _FakeResult_0<void, _i6.Failure>(
                this,
                Invocation.method(#markAllRead, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<int, _i6.Failure>> getUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, []),
            returnValue: _i4.Future<_i2.Result<int, _i6.Failure>>.value(
              _FakeResult_0<int, _i6.Failure>(
                this,
                Invocation.method(#getUnreadCount, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<int, _i6.Failure>>);
}

/// A class which mocks [NotificationRealtimeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRealtimeService extends _i1.Mock
    implements _i7.NotificationRealtimeService {
  MockNotificationRealtimeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isSubscribed =>
      (super.noSuchMethod(Invocation.getter(#isSubscribed), returnValue: false)
          as bool);

  @override
  void subscribe({
    required String? userId,
    required _i7.OnNewNotification? onNewNotification,
  }) => super.noSuchMethod(
    Invocation.method(#subscribe, [], {
      #userId: userId,
      #onNewNotification: onNewNotification,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unsubscribe() => super.noSuchMethod(
    Invocation.method(#unsubscribe, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
