// Mocks generated by Mockito 5.4.6 from annotations
// in dabbler/test/features/meetups/meetup_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dabbler/features/meetups/data/datasources/meetup_datasource.dart'
    as _i2;
import 'package:dabbler/features/meetups/domain/models/meetup_inputs.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MeetupDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeetupDataSource extends _i1.Mock implements _i2.MeetupDataSource {
  @override
  _i3.Future<List<Map<String, dynamic>>> fetchMeetupList({
    String? sportId,
    required int? limit,
    required int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMeetupList, [], {
              #sportId: sportId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> nearby(
    double? lat,
    double? lng,
    double? radius,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#nearby, [lat, lng, radius]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>> card(
    String? meetupId,
    String? profileType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#card, [meetupId, profileType]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> attendees(
    String? meetupId, {
    String? status,
    required int? limit,
    required int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #attendees,
              [meetupId],
              {#status: status, #limit: limit, #offset: offset},
            ),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>> canRsvp(String? meetupId) =>
      (super.noSuchMethod(
            Invocation.method(#canRsvp, [meetupId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<bool> canCreate(String? actorProfileId) =>
      (super.noSuchMethod(
            Invocation.method(#canCreate, [actorProfileId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<Map<String, dynamic>>> soloSports() =>
      (super.noSuchMethod(
            Invocation.method(#soloSports, []),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> sportVariants(String? sportId) =>
      (super.noSuchMethod(
            Invocation.method(#sportVariants, [sportId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<String> create(
    _i4.CreateMeetupInput? input, {
    required String? actorType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [input], {#actorType: actorType}),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#create, [input], {#actorType: actorType}),
              ),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#create, [input], {#actorType: actorType}),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> rsvp(
    String? meetupId,
    String? action, {
    String? profileId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #rsvp,
              [meetupId, action],
              {#profileId: profileId},
            ),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(
                  #rsvp,
                  [meetupId, action],
                  {#profileId: profileId},
                ),
              ),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(
                  #rsvp,
                  [meetupId, action],
                  {#profileId: profileId},
                ),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> cancel(String? meetupId) =>
      (super.noSuchMethod(
            Invocation.method(#cancel, [meetupId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> update(_i4.UpdateMeetupInput? input) =>
      (super.noSuchMethod(
            Invocation.method(#update, [input]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
