import 'package:flutter/material.dart';

/// Chat-specific enums.
/// Post enums have been removed — rebuilt in data/models layer.

/// Types of chat messages
enum MessageType {
  text('text', 'Text Message', Icons.message),
  image('image', 'Image', Icons.image),
  video('video', 'Video', Icons.videocam),
  audio('audio', 'Audio', Icons.mic),
  file('file', 'File', Icons.attach_file),
  location('location', 'Location', Icons.location_city),
  gameInvite('game_invite', 'Game Invite', Icons.sports),
  system('system', 'System Message', Icons.info);

  const MessageType(this.value, this.displayName, this.icon);

  final String value;
  final String displayName;
  final IconData icon;

  /// Get MessageType from string value
  static MessageType? fromValue(String value) {
    for (final type in MessageType.values) {
      if (type.value == value) return type;
    }
    return null;
  }

  /// Check if message type supports media
  bool get isMedia =>
      this == MessageType.image ||
      this == MessageType.video ||
      this == MessageType.file;

  /// Check if message type is interactive
  bool get isInteractive => this == MessageType.gameInvite;

  /// Check if message is generated by system
  bool get isSystem => this == MessageType.system;
}

/// Status of chat messages
enum MessageStatus {
  sending('sending', 'Sending'),
  sent('sent', 'Sent'),
  delivered('delivered', 'Delivered'),
  read('read', 'Read'),
  failed('failed', 'Failed');

  const MessageStatus(this.value, this.displayName);

  final String value;
  final String displayName;

  /// Get MessageStatus from string value
  static MessageStatus? fromValue(String value) {
    for (final status in MessageStatus.values) {
      if (status.value == value) return status;
    }
    return null;
  }

  /// Check if message was successfully sent
  bool get isSent =>
      this == MessageStatus.sent ||
      this == MessageStatus.delivered ||
      this == MessageStatus.read;

  /// Check if message failed to send
  bool get isFailed => this == MessageStatus.failed;

  /// Check if message is in progress
  bool get isPending => this == MessageStatus.sending;
}
