// Mocks generated by Mockito 5.4.6 from annotations
// in dabbler/test/helpers/mock_factories.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dabbler/core/fp/failure.dart' as _i6;
import 'package:dabbler/core/fp/result.dart' as _i2;
import 'package:dabbler/data/models/authentication/auth_session.dart' as _i5;
import 'package:dabbler/data/models/authentication/user.dart' as _i7;
import 'package:dabbler/data/models/games/booking.dart' as _i14;
import 'package:dabbler/data/models/games/game.dart' as _i10;
import 'package:dabbler/data/models/games/player.dart' as _i12;
import 'package:dabbler/data/models/games/sport_config.dart' as _i17;
import 'package:dabbler/data/models/games/venue.dart' as _i16;
import 'package:dabbler/features/auth_onboarding/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:dabbler/features/games/domain/repositories/bookings_repository.dart'
    as _i13;
import 'package:dabbler/features/games/domain/repositories/games_repository.dart'
    as _i8;
import 'package:dabbler/features/games/domain/repositories/venues_repository.dart'
    as _i15;
import 'package:fpdart/fpdart.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T, E> extends _i1.SmartFake implements _i2.Result<T, E> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<_i5.AuthSession, _i6.Failure>> signInWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i4.Future<_i2.Result<_i5.AuthSession, _i6.Failure>>.value(
                  _FakeResult_0<_i5.AuthSession, _i6.Failure>(
                    this,
                    Invocation.method(#signInWithEmail, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<_i5.AuthSession, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<_i5.AuthSession, _i6.Failure>> signUp({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i4.Future<_i2.Result<_i5.AuthSession, _i6.Failure>>.value(
                  _FakeResult_0<_i5.AuthSession, _i6.Failure>(
                    this,
                    Invocation.method(#signUp, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<_i5.AuthSession, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<void, _i6.Failure>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<_i2.Result<void, _i6.Failure>>.value(
              _FakeResult_0<void, _i6.Failure>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<_i7.User, _i6.Failure>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i4.Future<_i2.Result<_i7.User, _i6.Failure>>.value(
              _FakeResult_0<_i7.User, _i6.Failure>(
                this,
                Invocation.method(#getCurrentUser, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i7.User, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<_i5.AuthSession, _i6.Failure>> getCurrentSession() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentSession, []),
            returnValue:
                _i4.Future<_i2.Result<_i5.AuthSession, _i6.Failure>>.value(
                  _FakeResult_0<_i5.AuthSession, _i6.Failure>(
                    this,
                    Invocation.method(#getCurrentSession, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<_i5.AuthSession, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<void, _i6.Failure>> resetPassword({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {#email: email}),
            returnValue: _i4.Future<_i2.Result<void, _i6.Failure>>.value(
              _FakeResult_0<void, _i6.Failure>(
                this,
                Invocation.method(#resetPassword, [], {#email: email}),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<void, _i6.Failure>> updatePassword({
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [], {#newPassword: newPassword}),
            returnValue: _i4.Future<_i2.Result<void, _i6.Failure>>.value(
              _FakeResult_0<void, _i6.Failure>(
                this,
                Invocation.method(#updatePassword, [], {
                  #newPassword: newPassword,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<_i5.AuthSession, _i6.Failure>> verifyOTP({
    required String? email,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOTP, [], {#email: email, #token: token}),
            returnValue:
                _i4.Future<_i2.Result<_i5.AuthSession, _i6.Failure>>.value(
                  _FakeResult_0<_i5.AuthSession, _i6.Failure>(
                    this,
                    Invocation.method(#verifyOTP, [], {
                      #email: email,
                      #token: token,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<_i5.AuthSession, _i6.Failure>>);
}

/// A class which mocks [GamesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGamesRepository extends _i1.Mock implements _i8.GamesRepository {
  MockGamesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i9.Either<_i6.Failure, _i10.Game>> createGame(
    Map<String, dynamic>? gameData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createGame, [gameData]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, _i10.Game>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, _i10.Game>>(
                this,
                Invocation.method(#createGame, [gameData]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, _i10.Game>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, _i10.Game>> updateGame(
    String? gameId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateGame, [gameId, updates]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, _i10.Game>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, _i10.Game>>(
                this,
                Invocation.method(#updateGame, [gameId, updates]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, _i10.Game>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, _i10.Game>> getGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getGame, [gameId]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, _i10.Game>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, _i10.Game>>(
                this,
                Invocation.method(#getGame, [gameId]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, _i10.Game>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>> getGames({
    Map<String, dynamic>? filters,
    int? page = 1,
    int? limit = 20,
    String? sortBy,
    bool? ascending = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGames, [], {
              #filters: filters,
              #page: page,
              #limit: limit,
              #sortBy: sortBy,
              #ascending: ascending,
            }),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i10.Game>>>(
                    this,
                    Invocation.method(#getGames, [], {
                      #filters: filters,
                      #page: page,
                      #limit: limit,
                      #sortBy: sortBy,
                      #ascending: ascending,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> joinGame(
    String? gameId,
    String? playerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#joinGame, [gameId, playerId]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#joinGame, [gameId, playerId]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> leaveGame(
    String? gameId,
    String? playerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#leaveGame, [gameId, playerId]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#leaveGame, [gameId, playerId]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> cancelGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelGame, [gameId]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#cancelGame, [gameId]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>> getMyGames(
    String? userId, {
    String? status,
    String? sportId,
    bool? ascending = true,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMyGames,
              [userId],
              {
                #status: status,
                #sportId: sportId,
                #ascending: ascending,
                #page: page,
                #limit: limit,
              },
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i10.Game>>>(
                    this,
                    Invocation.method(
                      #getMyGames,
                      [userId],
                      {
                        #status: status,
                        #sportId: sportId,
                        #ascending: ascending,
                        #page: page,
                        #limit: limit,
                      },
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>> searchGames(
    String? query, {
    Map<String, dynamic>? filters,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchGames,
              [query],
              {#filters: filters, #page: page, #limit: limit},
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i10.Game>>>(
                    this,
                    Invocation.method(
                      #searchGames,
                      [query],
                      {#filters: filters, #page: page, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>> getNearbyGames(
    double? latitude,
    double? longitude,
    double? radiusKm, {
    Map<String, dynamic>? filters,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getNearbyGames,
              [latitude, longitude, radiusKm],
              {#filters: filters, #page: page, #limit: limit},
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i10.Game>>>(
                    this,
                    Invocation.method(
                      #getNearbyGames,
                      [latitude, longitude, radiusKm],
                      {#filters: filters, #page: page, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>> getGamesBySport(
    String? sportType, {
    Map<String, dynamic>? filters,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getGamesBySport,
              [sportType],
              {#filters: filters, #page: page, #limit: limit},
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i10.Game>>>(
                    this,
                    Invocation.method(
                      #getGamesBySport,
                      [sportType],
                      {#filters: filters, #page: page, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>> getTrendingGames({
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTrendingGames, [], {
              #page: page,
              #limit: limit,
            }),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i10.Game>>>(
                    this,
                    Invocation.method(#getTrendingGames, [], {
                      #page: page,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>> getRecommendedGames(
    String? userId, {
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRecommendedGames,
              [userId],
              {#page: page, #limit: limit},
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i10.Game>>>(
                    this,
                    Invocation.method(
                      #getRecommendedGames,
                      [userId],
                      {#page: page, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> updateGameStatus(
    String? gameId,
    _i10.GameStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateGameStatus, [gameId, status]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#updateGameStatus, [gameId, status]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> invitePlayersToGame(
    String? gameId,
    List<String>? playerIds,
    String? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#invitePlayersToGame, [
              gameId,
              playerIds,
              message,
            ]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#invitePlayersToGame, [
                  gameId,
                  playerIds,
                  message,
                ]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> respondToGameInvitation(
    String? gameId,
    String? playerId,
    bool? accepted,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#respondToGameInvitation, [
              gameId,
              playerId,
              accepted,
            ]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#respondToGameInvitation, [
                  gameId,
                  playerId,
                  accepted,
                ]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>> getUserGameStats(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserGameStats, [userId]),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>.value(
                  _i11.dummyValue<
                    _i9.Either<_i6.Failure, Map<String, dynamic>>
                  >(this, Invocation.method(#getUserGameStats, [userId])),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> reportGame(
    String? gameId,
    String? reason,
    String? description,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reportGame, [gameId, reason, description]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#reportGame, [gameId, reason, description]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> toggleGameFavorite(
    String? gameId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleGameFavorite, [gameId, userId]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#toggleGameFavorite, [gameId, userId]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>> getFavoriteGames(
    String? userId, {
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFavoriteGames,
              [userId],
              {#page: page, #limit: limit},
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i10.Game>>>(
                    this,
                    Invocation.method(
                      #getFavoriteGames,
                      [userId],
                      {#page: page, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> canUserJoinGame(
    String? gameId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#canUserJoinGame, [gameId, userId]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#canUserJoinGame, [gameId, userId]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>> getGameHistory(
    String? userId, {
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getGameHistory,
              [userId],
              {#page: page, #limit: limit},
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i10.Game>>>(
                    this,
                    Invocation.method(
                      #getGameHistory,
                      [userId],
                      {#page: page, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i10.Game>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, _i10.Game>> duplicateGame(
    String? gameId,
    DateTime? newDate,
    String? newStartTime,
    String? newEndTime,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#duplicateGame, [
              gameId,
              newDate,
              newStartTime,
              newEndTime,
            ]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, _i10.Game>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, _i10.Game>>(
                this,
                Invocation.method(#duplicateGame, [
                  gameId,
                  newDate,
                  newStartTime,
                  newEndTime,
                ]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, _i10.Game>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i12.Player>>> getGamePlayers(
    String? gameId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGamePlayers, [gameId]),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i12.Player>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i12.Player>>>(
                    this,
                    Invocation.method(#getGamePlayers, [gameId]),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i12.Player>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> isPlayerInGame(
    String? gameId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isPlayerInGame, [gameId, userId]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#isPlayerInGame, [gameId, userId]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, int?>> getWaitlistPosition(
    String? gameId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWaitlistPosition, [gameId, userId]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, int?>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, int?>>(
                this,
                Invocation.method(#getWaitlistPosition, [gameId, userId]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, int?>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> hasPendingJoinRequest(
    String? gameId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#hasPendingJoinRequest, [gameId, userId]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#hasPendingJoinRequest, [gameId, userId]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> cancelJoinRequest(
    String? gameId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cancelJoinRequest, [gameId, userId]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#cancelJoinRequest, [gameId, userId]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);
}

/// A class which mocks [BookingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookingsRepository extends _i1.Mock
    implements _i13.BookingsRepository {
  MockBookingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i9.Either<_i6.Failure, _i14.Booking>> createBooking(
    Map<String, dynamic>? bookingData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createBooking, [bookingData]),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, _i14.Booking>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, _i14.Booking>>(
                    this,
                    Invocation.method(#createBooking, [bookingData]),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, _i14.Booking>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, _i14.Booking>> getBooking(
    String? bookingId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBooking, [bookingId]),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, _i14.Booking>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, _i14.Booking>>(
                    this,
                    Invocation.method(#getBooking, [bookingId]),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, _i14.Booking>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> cancelBooking(
    String? bookingId,
    String? reason,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cancelBooking, [bookingId, reason]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#cancelBooking, [bookingId, reason]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i14.Booking>>> getMyBookings(
    String? userId, {
    _i13.BookingFilters? filters,
    int? page = 1,
    int? limit = 20,
    String? sortBy,
    bool? ascending = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMyBookings,
              [userId],
              {
                #filters: filters,
                #page: page,
                #limit: limit,
                #sortBy: sortBy,
                #ascending: ascending,
              },
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i14.Booking>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i14.Booking>>>(
                    this,
                    Invocation.method(
                      #getMyBookings,
                      [userId],
                      {
                        #filters: filters,
                        #page: page,
                        #limit: limit,
                        #sortBy: sortBy,
                        #ascending: ascending,
                      },
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i14.Booking>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i14.Booking>>> getVenueBookings(
    String? venueId,
    DateTime? date, {
    String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getVenueBookings,
              [venueId, date],
              {#status: status},
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i14.Booking>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i14.Booking>>>(
                    this,
                    Invocation.method(
                      #getVenueBookings,
                      [venueId, date],
                      {#status: status},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i14.Booking>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> updateBookingStatus(
    String? bookingId,
    _i14.BookingStatus? status, {
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateBookingStatus,
              [bookingId, status],
              {#notes: notes},
            ),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(
                  #updateBookingStatus,
                  [bookingId, status],
                  {#notes: notes},
                ),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> updatePaymentStatus(
    String? bookingId,
    _i14.PaymentStatus? status, {
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updatePaymentStatus,
              [bookingId, status],
              {#transactionId: transactionId},
            ),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(
                  #updatePaymentStatus,
                  [bookingId, status],
                  {#transactionId: transactionId},
                ),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> checkSlotAvailability(
    String? venueId,
    DateTime? date,
    String? startTime,
    String? endTime, {
    String? courtNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #checkSlotAvailability,
              [venueId, date, startTime, endTime],
              {#courtNumber: courtNumber},
            ),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(
                  #checkSlotAvailability,
                  [venueId, date, startTime, endTime],
                  {#courtNumber: courtNumber},
                ),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i14.Booking>>> getBookingConflicts(
    String? venueId,
    DateTime? date,
    String? startTime,
    String? endTime, {
    String? excludeBookingId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getBookingConflicts,
              [venueId, date, startTime, endTime],
              {#excludeBookingId: excludeBookingId},
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i14.Booking>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i14.Booking>>>(
                    this,
                    Invocation.method(
                      #getBookingConflicts,
                      [venueId, date, startTime, endTime],
                      {#excludeBookingId: excludeBookingId},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i14.Booking>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, _i14.Booking>> rescheduleBooking(
    String? bookingId,
    DateTime? newDate,
    String? newStartTime,
    String? newEndTime,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#rescheduleBooking, [
              bookingId,
              newDate,
              newStartTime,
              newEndTime,
            ]),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, _i14.Booking>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, _i14.Booking>>(
                    this,
                    Invocation.method(#rescheduleBooking, [
                      bookingId,
                      newDate,
                      newStartTime,
                      newEndTime,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, _i14.Booking>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> checkInBooking(
    String? bookingId,
    String? checkedInBy,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkInBooking, [bookingId, checkedInBy]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#checkInBooking, [bookingId, checkedInBy]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> checkOutBooking(
    String? bookingId,
    String? actualUsageDuration,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkOutBooking, [
              bookingId,
              actualUsageDuration,
            ]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#checkOutBooking, [
                  bookingId,
                  actualUsageDuration,
                ]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>> getUserBookingStats(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserBookingStats, [userId]),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>.value(
                  _i11.dummyValue<
                    _i9.Either<_i6.Failure, Map<String, dynamic>>
                  >(this, Invocation.method(#getUserBookingStats, [userId])),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>
  getVenueBookingStats(
    String? venueId, {
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getVenueBookingStats,
              [venueId],
              {#startDate: startDate, #endDate: endDate},
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>.value(
                  _i11.dummyValue<
                    _i9.Either<_i6.Failure, Map<String, dynamic>>
                  >(
                    this,
                    Invocation.method(
                      #getVenueBookingStats,
                      [venueId],
                      {#startDate: startDate, #endDate: endDate},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> requestRefund(
    String? bookingId,
    String? reason,
    double? refundAmount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#requestRefund, [
              bookingId,
              reason,
              refundAmount,
            ]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#requestRefund, [
                  bookingId,
                  reason,
                  refundAmount,
                ]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> processRefund(
    String? bookingId,
    double? refundAmount,
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#processRefund, [
              bookingId,
              refundAmount,
              transactionId,
            ]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#processRefund, [
                  bookingId,
                  refundAmount,
                  transactionId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i14.Booking>>> getUpcomingBookings(
    String? userId, {
    int? days = 7,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUpcomingBookings,
              [userId],
              {#days: days, #page: page, #limit: limit},
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i14.Booking>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i14.Booking>>>(
                    this,
                    Invocation.method(
                      #getUpcomingBookings,
                      [userId],
                      {#days: days, #page: page, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i14.Booking>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i14.Booking>>> getPastBookings(
    String? userId, {
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPastBookings,
              [userId],
              {#page: page, #limit: limit},
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i14.Booking>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i14.Booking>>>(
                    this,
                    Invocation.method(
                      #getPastBookings,
                      [userId],
                      {#page: page, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i14.Booking>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i14.Booking>>> getTodayBookings(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTodayBookings, [userId]),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i14.Booking>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i14.Booking>>>(
                    this,
                    Invocation.method(#getTodayBookings, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i14.Booking>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> sendBookingConfirmation(
    String? bookingId,
    String? method,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendBookingConfirmation, [bookingId, method]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#sendBookingConfirmation, [
                  bookingId,
                  method,
                ]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> sendBookingReminder(
    String? bookingId,
    String? method,
    int? minutesBefore,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendBookingReminder, [
              bookingId,
              method,
              minutesBefore,
            ]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#sendBookingReminder, [
                  bookingId,
                  method,
                  minutesBefore,
                ]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<Map<String, dynamic>>>>
  getBookingReminders(String? userId, {bool? activeOnly = true}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getBookingReminders,
              [userId],
              {#activeOnly: activeOnly},
            ),
            returnValue:
                _i4.Future<
                  _i9.Either<_i6.Failure, List<Map<String, dynamic>>>
                >.value(
                  _i11.dummyValue<
                    _i9.Either<_i6.Failure, List<Map<String, dynamic>>>
                  >(
                    this,
                    Invocation.method(
                      #getBookingReminders,
                      [userId],
                      {#activeOnly: activeOnly},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<Map<String, dynamic>>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> setupBookingReminders(
    String? bookingId,
    List<int>? minutesBefore,
    List<String>? methods,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setupBookingReminders, [
              bookingId,
              minutesBefore,
              methods,
            ]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#setupBookingReminders, [
                  bookingId,
                  minutesBefore,
                  methods,
                ]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, _i14.Booking>> extendBooking(
    String? bookingId,
    int? additionalMinutes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#extendBooking, [bookingId, additionalMinutes]),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, _i14.Booking>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, _i14.Booking>>(
                    this,
                    Invocation.method(#extendBooking, [
                      bookingId,
                      additionalMinutes,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, _i14.Booking>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, int>> getAvailableExtensionTime(
    String? bookingId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableExtensionTime, [bookingId]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, int>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, int>>(
                this,
                Invocation.method(#getAvailableExtensionTime, [bookingId]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, int>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> addBookingSpecialRequests(
    String? bookingId,
    String? requests,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addBookingSpecialRequests, [
              bookingId,
              requests,
            ]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#addBookingSpecialRequests, [
                  bookingId,
                  requests,
                ]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> updatePaymentMethod(
    String? bookingId,
    String? paymentMethod,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePaymentMethod, [bookingId, paymentMethod]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#updatePaymentMethod, [
                  bookingId,
                  paymentMethod,
                ]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>> getBookingReceipt(
    String? bookingId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBookingReceipt, [bookingId]),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>.value(
                  _i11.dummyValue<
                    _i9.Either<_i6.Failure, Map<String, dynamic>>
                  >(this, Invocation.method(#getBookingReceipt, [bookingId])),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, String>> downloadBookingReceiptPdf(
    String? bookingId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#downloadBookingReceiptPdf, [bookingId]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, String>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, String>>(
                this,
                Invocation.method(#downloadBookingReceiptPdf, [bookingId]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, String>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> shareBooking(
    String? bookingId,
    String? method,
    List<String>? recipients,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#shareBooking, [bookingId, method, recipients]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#shareBooking, [
                  bookingId,
                  method,
                  recipients,
                ]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, String>> getBookingQrCode(
    String? bookingId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBookingQrCode, [bookingId]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, String>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, String>>(
                this,
                Invocation.method(#getBookingQrCode, [bookingId]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, String>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, _i14.Booking>> validateBookingQrCode(
    String? qrCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validateBookingQrCode, [qrCode]),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, _i14.Booking>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, _i14.Booking>>(
                    this,
                    Invocation.method(#validateBookingQrCode, [qrCode]),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, _i14.Booking>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>
  getBookingPriceBreakdown(
    String? venueId,
    DateTime? date,
    String? startTime,
    String? endTime,
    String? courtNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBookingPriceBreakdown, [
              venueId,
              date,
              startTime,
              endTime,
              courtNumber,
            ]),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>.value(
                  _i11.dummyValue<
                    _i9.Either<_i6.Failure, Map<String, dynamic>>
                  >(
                    this,
                    Invocation.method(#getBookingPriceBreakdown, [
                      venueId,
                      date,
                      startTime,
                      endTime,
                      courtNumber,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>> applyPromoCode(
    String? bookingId,
    String? promoCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#applyPromoCode, [bookingId, promoCode]),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>.value(
                  _i11.dummyValue<
                    _i9.Either<_i6.Failure, Map<String, dynamic>>
                  >(
                    this,
                    Invocation.method(#applyPromoCode, [bookingId, promoCode]),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<Map<String, dynamic>>>>
  getAvailablePromoCodes(String? userId, String? venueId) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailablePromoCodes, [userId, venueId]),
            returnValue:
                _i4.Future<
                  _i9.Either<_i6.Failure, List<Map<String, dynamic>>>
                >.value(
                  _i11.dummyValue<
                    _i9.Either<_i6.Failure, List<Map<String, dynamic>>>
                  >(
                    this,
                    Invocation.method(#getAvailablePromoCodes, [
                      userId,
                      venueId,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<Map<String, dynamic>>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> rateBooking(
    String? bookingId,
    double? rating,
    String? review,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#rateBooking, [bookingId, rating, review]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#rateBooking, [bookingId, rating, review]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>> getBookingReviews(
    String? bookingId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBookingReviews, [bookingId]),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>.value(
                  _i11.dummyValue<
                    _i9.Either<_i6.Failure, Map<String, dynamic>>
                  >(this, Invocation.method(#getBookingReviews, [bookingId])),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> reportBookingIssue(
    String? bookingId,
    String? issueType,
    String? description,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reportBookingIssue, [
              bookingId,
              issueType,
              description,
            ]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#reportBookingIssue, [
                  bookingId,
                  issueType,
                  description,
                ]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>> getBookingAnalytics(
    String? venueId, {
    DateTime? startDate,
    DateTime? endDate,
    String? groupBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getBookingAnalytics,
              [venueId],
              {#startDate: startDate, #endDate: endDate, #groupBy: groupBy},
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>.value(
                  _i11.dummyValue<
                    _i9.Either<_i6.Failure, Map<String, dynamic>>
                  >(
                    this,
                    Invocation.method(
                      #getBookingAnalytics,
                      [venueId],
                      {
                        #startDate: startDate,
                        #endDate: endDate,
                        #groupBy: groupBy,
                      },
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, double>> getNoShowRate(
    String? venueId, {
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getNoShowRate,
              [venueId],
              {#startDate: startDate, #endDate: endDate},
            ),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, double>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, double>>(
                this,
                Invocation.method(
                  #getNoShowRate,
                  [venueId],
                  {#startDate: startDate, #endDate: endDate},
                ),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, double>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> markAsNoShow(
    String? bookingId,
    String? reason,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markAsNoShow, [bookingId, reason]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#markAsNoShow, [bookingId, reason]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>
  getCancellationReasonsAnalytics(
    String? venueId, {
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCancellationReasonsAnalytics,
              [venueId],
              {#startDate: startDate, #endDate: endDate},
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>.value(
                  _i11.dummyValue<
                    _i9.Either<_i6.Failure, Map<String, dynamic>>
                  >(
                    this,
                    Invocation.method(
                      #getCancellationReasonsAnalytics,
                      [venueId],
                      {#startDate: startDate, #endDate: endDate},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>);
}

/// A class which mocks [VenuesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVenuesRepository extends _i1.Mock implements _i15.VenuesRepository {
  MockVenuesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>> getVenues({
    _i15.VenueFilters? filters,
    int? page = 1,
    int? limit = 20,
    String? sortBy,
    bool? ascending = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getVenues, [], {
              #filters: filters,
              #page: page,
              #limit: limit,
              #sortBy: sortBy,
              #ascending: ascending,
            }),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i16.Venue>>>(
                    this,
                    Invocation.method(#getVenues, [], {
                      #filters: filters,
                      #page: page,
                      #limit: limit,
                      #sortBy: sortBy,
                      #ascending: ascending,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, _i16.Venue>> getVenue(String? venueId) =>
      (super.noSuchMethod(
            Invocation.method(#getVenue, [venueId]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, _i16.Venue>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, _i16.Venue>>(
                this,
                Invocation.method(#getVenue, [venueId]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, _i16.Venue>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>> searchVenues(
    String? query, {
    double? latitude,
    double? longitude,
    double? radiusKm,
    _i15.VenueFilters? filters,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchVenues,
              [query],
              {
                #latitude: latitude,
                #longitude: longitude,
                #radiusKm: radiusKm,
                #filters: filters,
                #page: page,
                #limit: limit,
              },
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i16.Venue>>>(
                    this,
                    Invocation.method(
                      #searchVenues,
                      [query],
                      {
                        #latitude: latitude,
                        #longitude: longitude,
                        #radiusKm: radiusKm,
                        #filters: filters,
                        #page: page,
                        #limit: limit,
                      },
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>> getNearbyVenues(
    double? latitude,
    double? longitude,
    double? radiusKm, {
    _i15.VenueFilters? filters,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getNearbyVenues,
              [latitude, longitude, radiusKm],
              {#filters: filters, #page: page, #limit: limit},
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i16.Venue>>>(
                    this,
                    Invocation.method(
                      #getNearbyVenues,
                      [latitude, longitude, radiusKm],
                      {#filters: filters, #page: page, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i17.SportConfig>>> getVenueSports(
    String? venueId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getVenueSports, [venueId]),
            returnValue:
                _i4.Future<
                  _i9.Either<_i6.Failure, List<_i17.SportConfig>>
                >.value(
                  _i11.dummyValue<
                    _i9.Either<_i6.Failure, List<_i17.SportConfig>>
                  >(this, Invocation.method(#getVenueSports, [venueId])),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i17.SportConfig>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i15.TimeSlot>>> checkAvailability(
    String? venueId,
    DateTime? date, {
    String? startTime,
    String? endTime,
    String? sport,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #checkAvailability,
              [venueId, date],
              {#startTime: startTime, #endTime: endTime, #sport: sport},
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i15.TimeSlot>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i15.TimeSlot>>>(
                    this,
                    Invocation.method(
                      #checkAvailability,
                      [venueId, date],
                      {#startTime: startTime, #endTime: endTime, #sport: sport},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i15.TimeSlot>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>> getFeaturedVenues({
    int? page = 1,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFeaturedVenues, [], {
              #page: page,
              #limit: limit,
            }),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i16.Venue>>>(
                    this,
                    Invocation.method(#getFeaturedVenues, [], {
                      #page: page,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>> getVenuesBySport(
    String? sportType, {
    double? latitude,
    double? longitude,
    double? radiusKm,
    _i15.VenueFilters? filters,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getVenuesBySport,
              [sportType],
              {
                #latitude: latitude,
                #longitude: longitude,
                #radiusKm: radiusKm,
                #filters: filters,
                #page: page,
                #limit: limit,
              },
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i16.Venue>>>(
                    this,
                    Invocation.method(
                      #getVenuesBySport,
                      [sportType],
                      {
                        #latitude: latitude,
                        #longitude: longitude,
                        #radiusKm: radiusKm,
                        #filters: filters,
                        #page: page,
                        #limit: limit,
                      },
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>> getVenueReviews(
    String? venueId, {
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getVenueReviews,
              [venueId],
              {#page: page, #limit: limit},
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>.value(
                  _i11.dummyValue<
                    _i9.Either<_i6.Failure, Map<String, dynamic>>
                  >(
                    this,
                    Invocation.method(
                      #getVenueReviews,
                      [venueId],
                      {#page: page, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> addVenueReview(
    String? venueId,
    String? userId,
    double? rating,
    String? comment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addVenueReview, [
              venueId,
              userId,
              rating,
              comment,
            ]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#addVenueReview, [
                  venueId,
                  userId,
                  rating,
                  comment,
                ]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<String>>> getVenuePhotos(
    String? venueId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getVenuePhotos, [venueId]),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<String>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<String>>>(
                    this,
                    Invocation.method(#getVenuePhotos, [venueId]),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<String>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>
  getVenueOperatingHours(String? venueId) =>
      (super.noSuchMethod(
            Invocation.method(#getVenueOperatingHours, [venueId]),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>.value(
                  _i11.dummyValue<
                    _i9.Either<_i6.Failure, Map<String, dynamic>>
                  >(
                    this,
                    Invocation.method(#getVenueOperatingHours, [venueId]),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>> getVenuePricing(
    String? venueId, {
    String? sport,
    DateTime? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getVenuePricing,
              [venueId],
              {#sport: sport, #date: date},
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>.value(
                  _i11.dummyValue<
                    _i9.Either<_i6.Failure, Map<String, dynamic>>
                  >(
                    this,
                    Invocation.method(
                      #getVenuePricing,
                      [venueId],
                      {#sport: sport, #date: date},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> checkVenueAmenities(
    String? venueId,
    List<String>? requiredAmenities,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkVenueAmenities, [
              venueId,
              requiredAmenities,
            ]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#checkVenueAmenities, [
                  venueId,
                  requiredAmenities,
                ]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>> getVenueContactInfo(
    String? venueId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getVenueContactInfo, [venueId]),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>.value(
                  _i11.dummyValue<
                    _i9.Either<_i6.Failure, Map<String, dynamic>>
                  >(this, Invocation.method(#getVenueContactInfo, [venueId])),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>> getUserVenues(
    String? userId, {
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUserVenues,
              [userId],
              {#page: page, #limit: limit},
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i16.Venue>>>(
                    this,
                    Invocation.method(
                      #getUserVenues,
                      [userId],
                      {#page: page, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> reportVenue(
    String? venueId,
    String? reason,
    String? description,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reportVenue, [venueId, reason, description]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#reportVenue, [venueId, reason, description]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, bool>> toggleVenueFavorite(
    String? venueId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleVenueFavorite, [venueId, userId]),
            returnValue: _i4.Future<_i9.Either<_i6.Failure, bool>>.value(
              _i11.dummyValue<_i9.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#toggleVenueFavorite, [venueId, userId]),
              ),
            ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>> getFavoriteVenues(
    String? userId, {
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFavoriteVenues,
              [userId],
              {#page: page, #limit: limit},
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i16.Venue>>>(
                    this,
                    Invocation.method(
                      #getFavoriteVenues,
                      [userId],
                      {#page: page, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<Map<String, dynamic>>>>
  getVenueBookingHistory(
    String? venueId, {
    DateTime? startDate,
    DateTime? endDate,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getVenueBookingHistory,
              [venueId],
              {
                #startDate: startDate,
                #endDate: endDate,
                #page: page,
                #limit: limit,
              },
            ),
            returnValue:
                _i4.Future<
                  _i9.Either<_i6.Failure, List<Map<String, dynamic>>>
                >.value(
                  _i11.dummyValue<
                    _i9.Either<_i6.Failure, List<Map<String, dynamic>>>
                  >(
                    this,
                    Invocation.method(
                      #getVenueBookingHistory,
                      [venueId],
                      {
                        #startDate: startDate,
                        #endDate: endDate,
                        #page: page,
                        #limit: limit,
                      },
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<Map<String, dynamic>>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>
  getVenueUtilizationStats(
    String? venueId, {
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getVenueUtilizationStats,
              [venueId],
              {#startDate: startDate, #endDate: endDate},
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>.value(
                  _i11.dummyValue<
                    _i9.Either<_i6.Failure, Map<String, dynamic>>
                  >(
                    this,
                    Invocation.method(
                      #getVenueUtilizationStats,
                      [venueId],
                      {#startDate: startDate, #endDate: endDate},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>> getRecommendedVenues(
    String? userId, {
    double? latitude,
    double? longitude,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRecommendedVenues,
              [userId],
              {
                #latitude: latitude,
                #longitude: longitude,
                #page: page,
                #limit: limit,
              },
            ),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i16.Venue>>>(
                    this,
                    Invocation.method(
                      #getRecommendedVenues,
                      [userId],
                      {
                        #latitude: latitude,
                        #longitude: longitude,
                        #page: page,
                        #limit: limit,
                      },
                    ),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>> getVenuePeakHours(
    String? venueId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getVenuePeakHours, [venueId]),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>.value(
                  _i11.dummyValue<
                    _i9.Either<_i6.Failure, Map<String, dynamic>>
                  >(this, Invocation.method(#getVenuePeakHours, [venueId])),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>> checkVenueCapacity(
    String? venueId,
    DateTime? dateTime,
    String? sport,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkVenueCapacity, [venueId, dateTime, sport]),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>.value(
                  _i11.dummyValue<
                    _i9.Either<_i6.Failure, Map<String, dynamic>>
                  >(
                    this,
                    Invocation.method(#checkVenueCapacity, [
                      venueId,
                      dateTime,
                      sport,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>
  getVenueWeatherSuitability(String? venueId) =>
      (super.noSuchMethod(
            Invocation.method(#getVenueWeatherSuitability, [venueId]),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>.value(
                  _i11.dummyValue<
                    _i9.Either<_i6.Failure, Map<String, dynamic>>
                  >(
                    this,
                    Invocation.method(#getVenueWeatherSuitability, [venueId]),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>>
  getVenuesWithPromotions({
    double? latitude,
    double? longitude,
    double? radiusKm,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getVenuesWithPromotions, [], {
              #latitude: latitude,
              #longitude: longitude,
              #radiusKm: radiusKm,
              #page: page,
              #limit: limit,
            }),
            returnValue:
                _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>>.value(
                  _i11.dummyValue<_i9.Either<_i6.Failure, List<_i16.Venue>>>(
                    this,
                    Invocation.method(#getVenuesWithPromotions, [], {
                      #latitude: latitude,
                      #longitude: longitude,
                      #radiusKm: radiusKm,
                      #page: page,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i9.Either<_i6.Failure, List<_i16.Venue>>>);
}
