// The bottom-nav shell and its four branches, moved whole.
//
// GENERATED BY HAND under KAN-124 (P0-3b). Route bodies are moved verbatim from
// lib/app/app_router.dart; only `_rootNavigatorKey` -> `rootNavigatorKey` and
// `_PlaceholderScreen` -> `PlaceholderScreen` are renamed. Declaration order is
// preserved by lib/app/app_router.dart's `_routes`, not by this file.

import 'package:go_router/go_router.dart';
import 'package:dabbler/features/home/presentation/screens/main_navigation_screen.dart';
import 'package:dabbler/features/home/presentation/screens/home_screen.dart';
import 'package:dabbler/features/explore/presentation/screens/venues_screen.dart';
import 'package:dabbler/features/explore/presentation/screens/games_screen.dart';
import 'package:dabbler/features/social/presentation/screens/real_friends_screen.dart' show RealFriendsScreen;
import 'package:dabbler/features/social/presentation/screens/real_friends_screen.dart';
import 'package:dabbler/utils/constants/route_constants.dart';
import 'package:dabbler/utils/transitions/page_transitions.dart';

// ── Shell route: persistent bottom-nav tabs with per-tab URLs ──
RouteBase get homeShellRoute =>
    StatefulShellRoute.indexedStack(
      builder: (context, state, navigationShell) {
        return MainNavigationScreen(navigationShell: navigationShell);
      },
      branches: [
        // Branch 0 — Home / Feeds
        StatefulShellBranch(
          routes: [
            GoRoute(
              path: RoutePaths.home,
              name: RouteNames.home,
              pageBuilder: (context, state) => FadeThroughTransitionPage(
                key: state.pageKey,
                child: const HomeScreen(),
              ),
            ),
          ],
        ),

        // Branch 1 — Community
        StatefulShellBranch(
          routes: [
            GoRoute(
              path: RoutePaths.community,
              name: RouteNames.community,
              pageBuilder: (context, state) => FadeThroughTransitionPage(
                key: state.pageKey,
                child: const RealFriendsScreen(),
              ),
            ),
          ],
        ),

        // Branch 2 — Venues
        StatefulShellBranch(
          routes: [
            GoRoute(
              path: RoutePaths.venuesTab,
              name: RouteNames.venuesTab,
              pageBuilder: (context, state) => FadeThroughTransitionPage(
                key: state.pageKey,
                child: const VenuesScreen(),
              ),
            ),
          ],
        ),

        // Branch 3 — Games
        StatefulShellBranch(
          routes: [
            GoRoute(
              path: RoutePaths.gamesTab,
              name: RouteNames.gamesTab,
              pageBuilder: (context, state) => FadeThroughTransitionPage(
                key: state.pageKey,
                child: const GamesScreen(),
              ),
            ),
          ],
        ),
      ],
    );
