// Identity — auth, onboarding, persona and username routes.
//
// GENERATED BY HAND under KAN-124 (P0-3b). Route bodies are moved verbatim from
// lib/app/app_router.dart; only `_rootNavigatorKey` -> `rootNavigatorKey` and
// `_PlaceholderScreen` -> `PlaceholderScreen` are renamed. Declaration order is
// preserved by lib/app/app_router.dart's `_routes`, not by this file.

import 'package:go_router/go_router.dart';
import 'package:dabbler/features/auth_onboarding/presentation/screens/landing_screen.dart';
import 'package:dabbler/features/auth_onboarding/presentation/screens/auth_welcome_screen.dart';
import 'package:dabbler/features/auth_onboarding/presentation/screens/email_input_screen.dart';
import 'package:dabbler/features/auth_onboarding/presentation/screens/otp_verification_screen.dart';
import 'package:dabbler/core/utils/identifier_detector.dart';
import 'package:dabbler/features/auth_onboarding/presentation/screens/create_user_information.dart';
import 'package:dabbler/features/auth_onboarding/presentation/screens/intent_selection_screen.dart';
import 'package:dabbler/features/auth_onboarding/presentation/screens/interests_selection_screen.dart';
import 'package:dabbler/features/auth_onboarding/presentation/screens/set_username_screen.dart';
import 'package:dabbler/features/auth_onboarding/presentation/screens/welcome_screen.dart';
import 'package:dabbler/features/auth_onboarding/presentation/screens/email_verification_screen.dart';
import 'package:dabbler/features/auth_onboarding/presentation/onboarding_scenarios/profile/onboarding_welcome_screen.dart';
import 'package:dabbler/features/auth_onboarding/presentation/screens/primary_sport_selection_screen.dart';
import 'package:dabbler/features/auth_onboarding/presentation/screens/forgot_password_screen.dart';
import 'package:dabbler/features/auth_onboarding/presentation/screens/email_password_screen.dart';
import 'package:dabbler/features/auth_onboarding/presentation/screens/reset_password_screen.dart';
import 'package:dabbler/features/auth_onboarding/presentation/screens/register_screen.dart';
import 'package:dabbler/features/auth_onboarding/presentation/screens/language_selection_screen.dart';
import 'package:dabbler/features/auth_onboarding/presentation/onboarding_scenarios/social/social_onboarding_welcome_screen.dart';
import 'package:dabbler/features/auth_onboarding/presentation/onboarding_scenarios/social/social_onboarding_friends_screen.dart';
import 'package:dabbler/features/auth_onboarding/presentation/onboarding_scenarios/social/social_onboarding_privacy_screen.dart';
import 'package:dabbler/features/auth_onboarding/presentation/onboarding_scenarios/social/social_onboarding_notifications_screen.dart';
import 'package:dabbler/features/auth_onboarding/presentation/onboarding_scenarios/social/social_onboarding_complete_screen.dart';
import 'package:dabbler/utils/constants/route_constants.dart';
import 'package:dabbler/features/auth_onboarding/presentation/providers/auth_providers.dart';
import 'package:dabbler/utils/transitions/page_transitions.dart';
import 'package:dabbler/app/app_router.dart';

// Landing page route
RouteBase get landingRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: '/landing',
      pageBuilder: (context, state) =>
          FadeTransitionPage(key: state.pageKey, child: const LandingPage()),
    );

// Auth-choice welcome screen (after landing)
RouteBase get authWelcomeRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.authWelcome,
      pageBuilder: (context, state) => FadeTransitionPage(
        key: state.pageKey,
        child: const AuthWelcomeScreen(),
      ),
    );

// Email input route
RouteBase get emailInputRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.emailInput,
      pageBuilder: (context, state) => FadeTransitionPage(
        key: state.pageKey,
        child: const EmailInputScreen(),
      ),
    );

// OTP verification route
RouteBase get otpVerificationRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.otpVerification,
      pageBuilder: (context, state) {
        final extra = state.extra;
        final identifier = extra is Map
            ? extra['identifier'] as String?
            : extra is Map
            ? extra['phone']
                  as String? // Legacy support
            : extra as String?;
        final identifierTypeStr = extra is Map
            ? extra['identifierType'] as String?
            : null;
        final userExistsBeforeOtp = extra is Map
            ? extra['userExistsBeforeOtp'] as bool?
            : null;

        // Parse identifier type
        IdentifierType? identifierType;
        if (identifierTypeStr == 'email') {
          identifierType = IdentifierType.email;
        } else if (identifierTypeStr == 'phone') {
          identifierType = IdentifierType.phone;
        }
        // If null, OtpVerificationScreen will auto-detect

        return FadeTransitionPage(
          key: state.pageKey,
          child: OtpVerificationScreen(
            identifier: identifier,
            identifierType: identifierType,
            userExistsBeforeOtp: userExistsBeforeOtp,
            phoneNumber: identifier, // Legacy support
          ),
        );
      },
    );

// Enter password route
RouteBase get enterPasswordRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.enterPassword,
      pageBuilder: (context, state) {
        final extra = state.extra;
        final email = extra is Map
            ? extra['email'] as String?
            : extra as String?;
        return FadeTransitionPage(
          key: state.pageKey,
          child: EnterPasswordScreen(email: email ?? ''),
        );
      },
    );

// Forgot password route
RouteBase get forgotPasswordRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.forgotPassword,
      pageBuilder: (context, state) => FadeTransitionPage(
        key: state.pageKey,
        child: const ForgotPasswordScreen(),
      ),
    );

// Reset password route
RouteBase get resetPasswordRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.resetPassword,
      pageBuilder: (context, state) => FadeTransitionPage(
        key: state.pageKey,
        child: const ResetPasswordScreen(),
      ),
    );

// Register route
RouteBase get registerRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.register,
      pageBuilder: (context, state) =>
          FadeTransitionPage(key: state.pageKey, child: const RegisterScreen()),
    );

// Create user information route
RouteBase get createUserInfoRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.createUserInfo,
      pageBuilder: (context, state) {
        final extra = state.extra;
        final email = extra is Map
            ? extra['email'] as String?
            : (extra is String ? extra : null);
        final phone = extra is Map ? extra['phone'] as String? : null;
        final forceNew = extra is Map ? extra['forceNew'] as bool? : false;
        return SlideTransitionPage(
          key: state.pageKey,
          child: CreateUserInformation(
            email: email,
            phone: phone,
            forceNew: forceNew ?? false,
          ),
          direction: SlideDirection.fromLeft,
        );
      },
    );

// Interests selection route (after intent selection)
RouteBase get interestsSelectionRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.interestsSelection,
      pageBuilder: (context, state) {
        return SlideTransitionPage(
          key: state.pageKey,
          child: const InterestsSelectionScreen(),
          direction: SlideDirection.fromLeft,
        );
      },
    );

// Intent selection route
RouteBase get intentSelectionRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.intentSelection,
      pageBuilder: (context, state) {
        return SlideTransitionPage(
          key: state.pageKey,
          child: const IntentSelectionScreen(),
          direction: SlideDirection.fromLeft,
        );
      },
    );

// DB-authoritative persona selection route (KAN-46).
// Reuses IntentSelectionScreen — the resume-state redirect (below) sends
// returning users with no persona recorded here rather than to an
// unregistered path and the error page.
RouteBase get onboardingPersonaSelectionRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.onboardingPersonaSelection,
      name: RouteNames.onboardingPersonaSelection,
      pageBuilder: (context, state) {
        return SlideTransitionPage(
          key: state.pageKey,
          child: const IntentSelectionScreen(),
          direction: SlideDirection.fromLeft,
        );
      },
    );

// Set username route (for phone users)
RouteBase get setUsernameRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.setUsername,
      pageBuilder: (context, state) {
        return SlideTransitionPage(
          key: state.pageKey,
          child: const SetUsernameScreen(),
          direction: SlideDirection.fromLeft,
        );
      },
    );

// Welcome route
RouteBase get welcomeRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.welcome,
      redirect: (context, state) {
        // Prevent returning to welcome after it has been dismissed
        if (!routerRefreshNotifier.needsPostLoginWelcome) {
          return RoutePaths.home;
        }
        return null;
      },
      pageBuilder: (context, state) {
        final extra = state.extra;
        final displayName = extra is Map
            ? extra['displayName'] as String?
            : 'Player';
        final personaType = extra is Map
            ? extra['personaType'] as String?
            : 'player';
        final isFirstTime = extra is Map ? extra['isFirstTime'] as bool? : true;
        return ScaleTransitionPage(
          key: state.pageKey,
          child: WelcomeScreen(
            displayName: displayName ?? 'Player',
            personaType: personaType ?? 'player',
            isFirstTime: isFirstTime ?? true,
          ),
        );
      },
    );

// Email verification pending route
RouteBase get emailVerificationRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.emailVerification,
      pageBuilder: (context, state) {
        final extra = state.extra;
        final onboardingData = extra is Map<String, dynamic> ? extra : null;
        return FadeTransitionPage(
          key: state.pageKey,
          child: EmailVerificationScreen(onboardingData: onboardingData),
        );
      },
    );

// Profile Onboarding Routes
RouteBase get onboardingWelcomeRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.onboardingWelcome,
      name: RouteNames.onboardingWelcome,
      pageBuilder: (context, state) => SlideTransitionPage(
        key: state.pageKey,
        child: const ProfileOnboardingWelcomeScreen(),
        direction: SlideDirection.fromLeft,
      ),
    );

// Interests Selection Route
// Note: This is the sports interests selection during onboarding
RouteBase get onboardingInterestsSelectionRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.onboardingInterestsSelection,
      name: RouteNames.onboardingInterestsSelection,
      pageBuilder: (context, state) => FadeTransitionPage(
        key: state.pageKey,
        child: const InterestsSelectionScreen(),
      ),
    );

// Primary Sport Selection Route
// Note: Select ONE sport to represent the user
RouteBase get onboardingPrimarySportRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.onboardingPrimarySport,
      name: RouteNames.onboardingPrimarySport,
      pageBuilder: (context, state) => FadeTransitionPage(
        key: state.pageKey,
        child: const PrimarySportSelectionScreen(),
      ),
    );

// Add Persona Flow Routes (from Settings)
RouteBase get addPersonaInterestsRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.addPersonaInterests,
      name: RouteNames.addPersonaInterests,
      pageBuilder: (context, state) => SharedAxisTransitionPage(
        key: state.pageKey,
        child: const InterestsSelectionScreen(
          mode: InterestsSelectionMode.addPersona,
        ),
        type: SharedAxisType.horizontal,
      ),
    );

RouteBase get addPersonaPrimarySportRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.addPersonaPrimarySport,
      name: RouteNames.addPersonaPrimarySport,
      pageBuilder: (context, state) => SharedAxisTransitionPage(
        key: state.pageKey,
        child: const PrimarySportSelectionScreen(
          mode: PrimarySportSelectionMode.addPersona,
        ),
        type: SharedAxisType.horizontal,
      ),
    );

RouteBase get addPersonaUsernameRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.addPersonaUsername,
      name: RouteNames.addPersonaUsername,
      pageBuilder: (context, state) => SharedAxisTransitionPage(
        key: state.pageKey,
        child: const SetUsernameScreen(mode: SetUsernameMode.addPersona),
        type: SharedAxisType.horizontal,
      ),
    );

RouteBase get addPersonaWelcomeRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.addPersonaWelcome,
      name: RouteNames.addPersonaWelcome,
      pageBuilder: (context, state) {
        final extra = state.extra as Map<String, dynamic>?;
        return FadeTransitionPage(
          key: state.pageKey,
          child: WelcomeScreen(
            displayName: extra?['displayName'] as String? ?? '',
            personaType: extra?['personaType'] as String? ?? 'player',
            isFirstTime: extra?['isFirstTime'] as bool? ?? false,
            isConversion: extra?['isConversion'] as bool? ?? false,
          ),
        );
      },
    );

RouteBase get settingsLanguageRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: '/settings/language',
      pageBuilder: (context, state) => SharedAxisTransitionPage(
        key: state.pageKey,
        child: const LanguageSelectionScreen(),
        type: SharedAxisType.horizontal,
      ),
    );

// Social Onboarding Routes
RouteBase get socialOnboardingWelcomeRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.socialOnboardingWelcome,
      name: RouteNames.socialOnboardingWelcome,
      pageBuilder: (context, state) => SlideTransitionPage(
        key: state.pageKey,
        child: const SocialOnboardingWelcomeScreen(),
        direction: SlideDirection.fromLeft,
      ),
    );

RouteBase get socialOnboardingFriendsRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.socialOnboardingFriends,
      name: RouteNames.socialOnboardingFriends,
      pageBuilder: (context, state) => SlideTransitionPage(
        key: state.pageKey,
        child: const SocialOnboardingFriendsScreen(),
        direction: SlideDirection.fromLeft,
      ),
    );

RouteBase get socialOnboardingPrivacyRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.socialOnboardingPrivacy,
      name: RouteNames.socialOnboardingPrivacy,
      pageBuilder: (context, state) => SlideTransitionPage(
        key: state.pageKey,
        child: const SocialOnboardingPrivacyScreen(),
        direction: SlideDirection.fromLeft,
      ),
    );

RouteBase get socialOnboardingNotificationsRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.socialOnboardingNotifications,
      name: RouteNames.socialOnboardingNotifications,
      pageBuilder: (context, state) => SlideTransitionPage(
        key: state.pageKey,
        child: const SocialOnboardingNotificationsScreen(),
        direction: SlideDirection.fromLeft,
      ),
    );

RouteBase get socialOnboardingCompleteRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.socialOnboardingComplete,
      name: RouteNames.socialOnboardingComplete,
      pageBuilder: (context, state) => ScaleTransitionPage(
        key: state.pageKey,
        child: const SocialOnboardingCompleteScreen(),
      ),
    );
