// Notifications routes.
//
// GENERATED BY HAND under KAN-124 (P0-3b). Route bodies are moved verbatim from
// lib/app/app_router.dart; only `_rootNavigatorKey` -> `rootNavigatorKey` and
// `_PlaceholderScreen` -> `PlaceholderScreen` are renamed. Declaration order is
// preserved by lib/app/app_router.dart's `_routes`, not by this file.

import 'package:go_router/go_router.dart';
import 'package:dabbler/core/config/feature_flags.dart';
import 'package:dabbler/features/notifications/presentation/screens/notifications_screen_v2.dart';
import 'package:dabbler/utils/constants/route_constants.dart';
import 'package:dabbler/utils/transitions/page_transitions.dart';
import 'package:dabbler/app/app_router.dart';

// Notifications route. Live and reachable from ordinary UI — not deep-link- or
// admin-only: app_top_bar.dart mounts a NotificationBadge and pushes this route
// from the bell button, and main_navigation_screen.dart and
// adaptive_destinations.dart both push it from main navigation. Access is gated
// on FeatureFlags.notifications.
RouteBase get notificationsRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.notifications,
      redirect: (context, state) {
        // Feature gate: the route is enabled by FeatureFlags.notifications.
        if (!FeatureFlags.notifications) {
          return RoutePaths.home;
        }
        return null; // Allow access if enabled
      },
      pageBuilder: (context, state) => FadeThroughTransitionPage(
        key: state.pageKey,
        child: const NotificationsScreenV2(),
      ),
    );
