// Notifications routes.
//
// GENERATED BY HAND under KAN-124 (P0-3b). Route bodies are moved verbatim from
// lib/app/app_router.dart; only `_rootNavigatorKey` -> `rootNavigatorKey` and
// `_PlaceholderScreen` -> `PlaceholderScreen` are renamed. Declaration order is
// preserved by lib/app/app_router.dart's `_routes`, not by this file.

import 'package:go_router/go_router.dart';
import 'package:dabbler/core/config/feature_flags.dart';
import 'package:dabbler/features/notifications/presentation/screens/notifications_screen_v2.dart';
import 'package:dabbler/utils/constants/route_constants.dart';
import 'package:dabbler/utils/transitions/page_transitions.dart';
import 'package:dabbler/app/app_router.dart';

// Notifications route (hidden for MVP)
// Route kept for deep links/admin access but UI entry points hidden
RouteBase get notificationsRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.notifications,
      redirect: (context, state) {
        // Notifications hidden for MVP
        if (!FeatureFlags.notifications) {
          return RoutePaths.home;
        }
        return null; // Allow access if enabled
      },
      pageBuilder: (context, state) => FadeThroughTransitionPage(
        key: state.pageKey,
        child: const NotificationsScreenV2(),
      ),
    );
