// Play & places — games, venues, explore and venue-submission routes.
//
// GENERATED BY HAND under KAN-124 (P0-3b). Route bodies are moved verbatim from
// lib/app/app_router.dart; only `_rootNavigatorKey` -> `rootNavigatorKey` and
// `_PlaceholderScreen` -> `PlaceholderScreen` are renamed. Declaration order is
// preserved by lib/app/app_router.dart's `_routes`, not by this file.

import 'package:go_router/go_router.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:dabbler/core/config/feature_flags.dart';
import 'package:dabbler/features/profile/presentation/providers/profile_providers.dart';
import 'package:dabbler/features/explore/presentation/screens/sports_screen.dart';
import 'package:dabbler/features/venues/presentation/screens/venue_detail_screen.dart';
import 'package:dabbler/features/games/presentation/screens/join_game/game_detail_screen.dart';
import 'package:dabbler/features/games/presentation/screens/game_composer_screen.dart';
import 'package:dabbler/features/activities/presentation/screens/activities_screen_v2.dart';
import 'package:dabbler/data/models/venue_submission_model.dart';
import 'package:dabbler/features/venue_submissions/presentation/screens/create_venue_submission_screen.dart';
import 'package:dabbler/features/venue_submissions/presentation/screens/my_venue_submissions_screen.dart';
import 'package:dabbler/features/venue_submissions/presentation/screens/venue_submission_detail_screen.dart';
import 'package:dabbler/utils/constants/route_constants.dart';
import 'package:dabbler/utils/transitions/page_transitions.dart';
import 'package:dabbler/app/app_router.dart';

// ── Deep-link entry routes ─────────────────────────────────────────────
// These top-level paths let the OS (Android / iOS) hand off
// dabbler://app/game/:gameId  and  dabbler://app/create-game  directly
// to the correct screen without needing to know the shell structure.

// /sports/games/:gameId — game detail (root-level, no shell/bottom-nav)
RouteBase get sportsGamesGameIdRoute =>
    GoRoute(
      path: '/sports/games/:gameId',
      name: RouteNames.gameDetail,
      parentNavigatorKey: rootNavigatorKey,
      pageBuilder: (context, state) {
        final gameId = state.pathParameters['gameId']!;
        // ?focus=requests (join-request notifications) scrolls the detail
        // screen down to the pending-requests card.
        final focus = state.uri.queryParameters['focus'];
        return SharedAxisTransitionPage(
          key: state.pageKey,
          child: GameDetailScreen(
            gameId: gameId,
            focusRequests: focus == 'requests',
          ),
          type: SharedAxisType.horizontal,
        );
      },
    );

// /sports/venues/:venueId — venue detail (root-level, no shell/bottom-nav)
RouteBase get sportsVenuesVenueIdRoute =>
    GoRoute(
      path: '/sports/venues/:venueId',
      name: RouteNames.venueDetail,
      parentNavigatorKey: rootNavigatorKey,
      pageBuilder: (context, state) {
        final venueId = state.pathParameters['venueId']!;
        return SharedAxisTransitionPage(
          key: state.pageKey,
          child: VenueDetailScreen(venueId: venueId),
          type: SharedAxisType.horizontal,
        );
      },
    );

// dabbler://app/game/:gameId → /sports/games/:gameId (root-level detail)
RouteBase get gameGameIdRoute =>
    GoRoute(
      path: '/game/:gameId',
      redirect: (context, state) {
        final gameId = state.pathParameters['gameId'];
        if (gameId == null || gameId.isEmpty) return RoutePaths.gamesTab;
        return '/sports/games/$gameId';
      },
    );

// Legacy /sports top-level redirect handled inside the shell branch above.
// Sports explore screen (direct access, feature-flagged)
RouteBase get sportsExploreRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.sportsExplore,
      name: RouteNames.sports,
      redirect: (context, state) {
        if (!FeatureFlags.enableGameBrowsing) {
          return RoutePaths.home;
        }
        return null;
      },
      pageBuilder: (context, state) => FadeThroughTransitionPage(
        key: state.pageKey,
        child: const ExploreScreen(),
      ),
    );

// Organiser Venue Submissions
RouteBase get myVenueSubmissionsRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.myVenueSubmissions,
      name: RouteNames.myVenueSubmissions,
      redirect: (context, state) {
        final container = ProviderScope.containerOf(context, listen: false);
        final profileState = container.read(profileControllerProvider);
        final profileType = profileState.profile?.profileType;
        if (profileType != 'organiser') {
          return RoutePaths.home;
        }
        return null;
      },
      pageBuilder: (context, state) => SharedAxisTransitionPage(
        key: state.pageKey,
        child: const MyVenueSubmissionsScreen(),
        type: SharedAxisType.horizontal,
      ),
      routes: [
        GoRoute(
          parentNavigatorKey: rootNavigatorKey,
          path: 'create',
          name: RouteNames.createVenueSubmission,
          pageBuilder: (context, state) {
            final initial = state.extra is VenueSubmissionModel
                ? state.extra as VenueSubmissionModel
                : null;
            return SharedAxisTransitionPage(
              key: state.pageKey,
              child: CreateVenueSubmissionScreen(initial: initial),
              type: SharedAxisType.horizontal,
            );
          },
        ),
        GoRoute(
          parentNavigatorKey: rootNavigatorKey,
          path: ':${RouteParams.submissionId}',
          name: RouteNames.venueSubmissionDetail,
          pageBuilder: (context, state) {
            final id = state.pathParameters[RouteParams.submissionId] ?? '';
            return SharedAxisTransitionPage(
              key: state.pageKey,
              child: VenueSubmissionDetailScreen(submissionId: id),
              type: SharedAxisType.horizontal,
            );
          },
        ),
      ],
    );

// Activities route
RouteBase get activitiesRoute =>
    GoRoute(
      parentNavigatorKey: rootNavigatorKey,
      path: RoutePaths.activities,
      name: RouteNames.activities,
      pageBuilder: (context, state) => FadeThroughTransitionPage(
        key: state.pageKey,
        child: const ActivitiesScreenV2(),
      ),
    );

// Game Creation Routes - Differentiated by profile type
// Organisers can create, players cannot (MVP)
RouteBase get createGameRoute =>
    GoRoute(
      path: RoutePaths.createGame,
      name: RouteNames.createGame,
      parentNavigatorKey: rootNavigatorKey,
      redirect: (context, state) async {
        // Check user's profile type and apply feature flags
        final container = ProviderScope.containerOf(context, listen: false);
        final profileState = container.read(profileControllerProvider);
        final profileType = profileState.profile?.profileType;

        // Block players from creating games if feature disabled
        if (profileType == 'player' && !FeatureFlags.enablePlayerGameCreation) {
          return RoutePaths.home;
        }

        // Block organisers from creating games if feature disabled
        if (profileType == 'organiser' &&
            !FeatureFlags.enableOrganiserGameCreation) {
          return RoutePaths.home;
        }

        // Allow access if profile type has permission
        return null;
      },
      // Drawer-style modal: leaves the top safe area exposed and lets the
      // composer's glass surface blur the screen behind it.
      pageBuilder: (context, state) => AdaptiveModalPage(
        key: state.pageKey,
        transparentSurface: true,
        child: const GameComposerScreen(),
      ),
    );

RouteBase get createGameBasicInfoRoute =>
    GoRoute(
      path: RoutePaths.createGameBasicInfo,
      name: RouteNames.createGameBasicInfo,
      parentNavigatorKey: rootNavigatorKey,
      redirect: (context, state) async {
        final container = ProviderScope.containerOf(context, listen: false);
        final profileState = container.read(profileControllerProvider);
        final profileType = profileState.profile?.profileType;

        if (profileType == 'player' && !FeatureFlags.enablePlayerGameCreation) {
          return RoutePaths.home;
        }
        if (profileType == 'organiser' &&
            !FeatureFlags.enableOrganiserGameCreation) {
          return RoutePaths.home;
        }
        return null;
      },
      pageBuilder: (context, state) => AdaptiveModalPage(
        key: state.pageKey,
        transparentSurface: true,
        child: const GameComposerScreen(),
      ),
    );

// Edit an existing game — same drawer as creation, prefilled. Host-only
// enforcement lives in rpc_update_game; the entry button is host-gated.
RouteBase get editGameRoute =>
    GoRoute(
      path: RoutePaths.editGame,
      name: RouteNames.editGame,
      parentNavigatorKey: rootNavigatorKey,
      pageBuilder: (context, state) => AdaptiveModalPage(
        key: state.pageKey,
        transparentSurface: true,
        child: GameComposerScreen(
          editGameId: state.pathParameters['gameId']!,
        ),
      ),
    );
