import 'dart:ui' show Color;

const theme = (
  activity: (
    primary: Color(0xFFCF3989),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFFCDEE8),
    onPrimaryContainer: Color(0xFF3A0026),
    secondary: Color(0xFFEB005A),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFFFF2FC),
    onSecondaryContainer: Color(0xFF3B0014),
    tertiary: Color(0xFFADB4FF),
    onTertiary: Color(0xFF00115A),
    tertiaryContainer: Color(0xFFE0E0FF),
    onTertiaryContainer: Color(0xFF000F52),
    error: Color(0xFFBA1A1A),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFDAD6),
    onErrorContainer: Color(0xFF410002),
    background: Color(0xFFFFFBFF),
    onBackground: Color(0xFF1C1B1E),
    surface: Color(0xFFFFFBFF),
    onSurface: Color(0xFF1C1B1E),
    surfaceVariant: Color(0xFFE8E0E6),
    onSurfaceVariant: Color(0xFF4B454C),
    outline: Color(0xFF7C757D),
    outlineVariant: Color(0xFFCBC4CB),
    surfaceTint: Color(0xFFCF3989),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFF312F33),
    inverseOnSurface: Color(0xFFF4EFF4),
    inversePrimary: Color(0xFFFFAFCE),
    primaryFixed: Color(0xFFFFD8E6),
    onPrimaryFixed: Color(0xFF3A0026),
    primaryFixedDim: Color(0xFFFFAFCE),
    onPrimaryFixedVariant: Color(0xFF6F0047),
    secondaryFixed: Color(0xFFFFD9E1),
    onSecondaryFixed: Color(0xFF3B0014),
    secondaryFixedDim: Color(0xFFFFB1C2),
    onSecondaryFixedVariant: Color(0xFF7F0031),
    tertiaryFixed: Color(0xFFE0E0FF),
    onTertiaryFixed: Color(0xFF000F52),
    tertiaryFixedDim: Color(0xFFC1C5FF),
    onTertiaryFixedVariant: Color(0xFF353A94),
    surfaceDim: Color(0xFFE2DEE3),
    surfaceBright: Color(0xFFFFFBFF),
    surfaceContainerLowest: Color(0xFFFFFFFF),
    surfaceContainerLow: Color(0xFFF9F6FA),
    surfaceContainer: Color(0xFFF3EFF3),
    surfaceContainerHigh: Color(0xFFECE7EC),
    surfaceContainerHighest: Color(0xFFE5E1E6),
  ),
);
