import 'dart:ui' show Color;

const theme = (
  main: (
    primary: Color(0xFF7328CE),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFEADDFF),
    onPrimaryContainer: Color(0xFF25005B),
    secondary: Color(0xFFA4008F),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFFEF1FF),
    onSecondaryContainer: Color(0xFF3C0030),
    tertiary: Color(0xFFFF3376),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFFFD9E1),
    onTertiaryContainer: Color(0xFF3B0014),
    error: Color(0xFFBA1A1A),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFDAD6),
    onErrorContainer: Color(0xFF410002),
    background: Color(0xFFFEF7FF),
    onBackground: Color(0xFF1D1B20),
    surface: Color(0xFFFEF7FF),
    onSurface: Color(0xFF1D1B20),
    surfaceVariant: Color(0xFFE7E0EC),
    onSurfaceVariant: Color(0xFF49454F),
    outline: Color(0xFF7A757F),
    outlineVariant: Color(0xFFCBC4CF),
    surfaceTint: Color(0xFF7328CE),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFF322F35),
    inverseOnSurface: Color(0xFFF5EFF7),
    inversePrimary: Color(0xFFD0BCFF),
    primaryFixed: Color(0xFFEADDFF),
    onPrimaryFixed: Color(0xFF25005B),
    primaryFixedDim: Color(0xFFD0BCFF),
    onPrimaryFixedVariant: Color(0xFF4F009A),
    secondaryFixed: Color(0xFFFFD7F1),
    onSecondaryFixed: Color(0xFF3C0030),
    secondaryFixedDim: Color(0xFFEFB1E2),
    onSecondaryFixedVariant: Color(0xFF6B005A),
    tertiaryFixed: Color(0xFFFFD9E1),
    onTertiaryFixed: Color(0xFF3B0014),
    tertiaryFixedDim: Color(0xFFFFB1C2),
    onTertiaryFixedVariant: Color(0xFF7F0031),
    surfaceDim: Color(0xFFDED8E1),
    surfaceBright: Color(0xFFFEF7FF),
    surfaceContainerLowest: Color(0xFFFFFFFF),
    surfaceContainerLow: Color(0xFFF7F2FA),
    surfaceContainer: Color(0xFFF3EDF7),
    surfaceContainerHigh: Color(0xFFECE6F0),
    surfaceContainerHighest: Color(0xFFE6E0E9),
  ),
);
