import 'dart:ui' show Color;

const theme = (
  social: (
    primary: Color(0xFF3473D7),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFA6DCFF),
    onPrimaryContainer: Color(0xFF001B3D),
    secondary: Color(0xFF65A8FF),
    onSecondary: Color(0xFF002C60),
    secondaryContainer: Color(0xFFE5F5FF),
    onSecondaryContainer: Color(0xFF001B3D),
    tertiary: Color(0xFF855BE2),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFE7DEFF),
    onTertiaryContainer: Color(0xFF270057),
    error: Color(0xFFBA1A1A),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFDAD6),
    onErrorContainer: Color(0xFF410002),
    background: Color(0xFFFDFBFF),
    onBackground: Color(0xFF1B1B1F),
    surface: Color(0xFFFDFBFF),
    onSurface: Color(0xFF1B1B1F),
    surfaceVariant: Color(0xFFE0E2EC),
    onSurfaceVariant: Color(0xFF44474F),
    outline: Color(0xFF74777F),
    outlineVariant: Color(0xFFC4C6D0),
    surfaceTint: Color(0xFF3473D7),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFF303034),
    inverseOnSurface: Color(0xFFF3EFF4),
    inversePrimary: Color(0xFFA6C8FF),
    primaryFixed: Color(0xFFD6E3FF),
    onPrimaryFixed: Color(0xFF001B3D),
    primaryFixedDim: Color(0xFFA6C8FF),
    onPrimaryFixedVariant: Color(0xFF00449B),
    secondaryFixed: Color(0xFFD4E3FF),
    onSecondaryFixed: Color(0xFF001B3D),
    secondaryFixedDim: Color(0xFFA4CBFF),
    onSecondaryFixedVariant: Color(0xFF003E7C),
    tertiaryFixed: Color(0xFFE7DEFF),
    onTertiaryFixed: Color(0xFF270057),
    tertiaryFixedDim: Color(0xFFCDBEFF),
    onTertiaryFixedVariant: Color(0xFF5523A8),
    surfaceDim: Color(0xFFDFE1EB),
    surfaceBright: Color(0xFFFDFBFF),
    surfaceContainerLowest: Color(0xFFFFFFFF),
    surfaceContainerLow: Color(0xFFF7F7FC),
    surfaceContainer: Color(0xFFF3F3F9),
    surfaceContainerHigh: Color(0xFFECEAF2),
    surfaceContainerHighest: Color(0xFFE6E3EC),
  ),
);
